
import javax.swing.JFrame;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaihunbek Mohammadullah
 * Date : 8/25/2021
 * This frame is the User Guide
 */
public class frmUserGuide extends javax.swing.JFrame {

    /**
     * Creates new form frmUserGuide
     */
    public frmUserGuide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblWhatAreRule = new javax.swing.JLabel();
        lblRules1 = new javax.swing.JLabel();
        lblRules2 = new javax.swing.JLabel();
        lblRule3 = new javax.swing.JLabel();
        lblRule4 = new javax.swing.JLabel();
        lblRule5 = new javax.swing.JLabel();
        lblRule6 = new javax.swing.JLabel();
        lblRule7 = new javax.swing.JLabel();
        lblHowToInstall = new javax.swing.JLabel();
        lblInstall1 = new javax.swing.JLabel();
        lblInstall2 = new javax.swing.JLabel();
        lblInstall3 = new javax.swing.JLabel();
        lblInstall4 = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();
        lblPipsAndMana = new javax.swing.JLabel();
        lblDamageOfSpell = new javax.swing.JLabel();
        lblScreenShotOfHUD = new javax.swing.JLabel();
        lblPassButton = new javax.swing.JLabel();
        lblUserStats = new javax.swing.JLabel();
        lblNextRoundBtn = new javax.swing.JLabel();
        lblCurrentRound = new javax.swing.JLabel();
        lblComputerStats = new javax.swing.JLabel();
        lblComputerDecision = new javax.swing.JLabel();
        lblUserDecision = new javax.swing.JLabel();
        lblCardSpells = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHowToPlay = new javax.swing.JLabel();
        lblPlay1 = new javax.swing.JLabel();
        lblPlay2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 3, 56)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(102, 0, 0));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("User Guide");

        lblWhatAreRule.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWhatAreRule.setForeground(new java.awt.Color(102, 0, 0));
        lblWhatAreRule.setText("What are the Rules?");

        lblRules1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRules1.setForeground(new java.awt.Color(51, 51, 51));
        lblRules1.setText("The user has health, mana and pips resources.");

        lblRules2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRules2.setForeground(new java.awt.Color(51, 51, 51));
        lblRules2.setText("Each spellcard requires a certain amount of pips and mana to be cast");

        lblRule3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRule3.setForeground(new java.awt.Color(51, 51, 51));
        lblRule3.setText("If the user runs out health or mana, he loses.");

        lblRule4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRule4.setForeground(new java.awt.Color(51, 51, 51));
        lblRule4.setText("Every round, the user gains one pip");

        lblRule5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRule5.setForeground(new java.awt.Color(51, 51, 51));
        lblRule5.setText("When the user passes, he does not cast a spell, ensuring that his pips increase.");

        lblRule6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRule6.setForeground(new java.awt.Color(51, 51, 51));
        lblRule6.setText("Each round, the user and computer will make a move. ");

        lblRule7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRule7.setForeground(new java.awt.Color(51, 51, 51));
        lblRule7.setText("The user can pass or cast a spell. The computer will pass or cast a spell at random.");

        lblHowToInstall.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHowToInstall.setForeground(new java.awt.Color(102, 0, 0));
        lblHowToInstall.setText("How to Run Game:");

        lblInstall1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInstall1.setText("1. Open NetBeans");

        lblInstall2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInstall2.setText("2. Click File > Open Project");

        lblInstall3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInstall3.setText("3. Navigate to game project");

        lblInstall4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInstall4.setText("4. Press F6 to Run. Enjoy!");

        lblCard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beyond\\Documents\\NetBeansProjects\\MohammadullahJaihunbekFinalProject\\orthrus.jpg")); // NOI18N

        lblPipsAndMana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPipsAndMana.setForeground(new java.awt.Color(102, 0, 0));
        lblPipsAndMana.setText("The pips and mana required --->");

        lblDamageOfSpell.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDamageOfSpell.setForeground(new java.awt.Color(102, 0, 0));
        lblDamageOfSpell.setText("The damage of the spell ------>");

        lblScreenShotOfHUD.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beyond\\Documents\\NetBeansProjects\\MohammadullahJaihunbekFinalProject\\userguidepic.jpg")); // NOI18N

        lblPassButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPassButton.setForeground(new java.awt.Color(0, 0, 102));
        lblPassButton.setText("Pass button ----->");

        lblUserStats.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserStats.setForeground(new java.awt.Color(0, 0, 102));
        lblUserStats.setText("User Stats ---->");

        lblNextRoundBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNextRoundBtn.setForeground(new java.awt.Color(0, 0, 102));
        lblNextRoundBtn.setText("<--- Next Round button");

        lblCurrentRound.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCurrentRound.setForeground(new java.awt.Color(0, 0, 102));
        lblCurrentRound.setText("Current Round ----->");

        lblComputerStats.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComputerStats.setForeground(new java.awt.Color(0, 0, 102));
        lblComputerStats.setText("<-- Computer stats");

        lblComputerDecision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComputerDecision.setForeground(new java.awt.Color(0, 0, 102));
        lblComputerDecision.setText("<--- Computer's decisions");

        lblUserDecision.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserDecision.setForeground(new java.awt.Color(0, 0, 102));
        lblUserDecision.setText("<--- User's decision");

        lblCardSpells.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCardSpells.setForeground(new java.awt.Color(0, 0, 102));
        lblCardSpells.setText("<--- User's cardspells");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHowToPlay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHowToPlay.setForeground(new java.awt.Color(102, 0, 0));
        lblHowToPlay.setText("How to Play?");

        lblPlay1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlay1.setText("To make a move, the user must select his choice, then click the 'Next Round' button");

        lblPlay2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlay2.setText("Here is how to read the HUD: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlay2)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassButton)
                                    .addComponent(lblCurrentRound)
                                    .addComponent(lblUserStats))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(lblScreenShotOfHUD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComputerStats)
                            .addComponent(lblNextRoundBtn)
                            .addComponent(lblUserDecision)
                            .addComponent(lblCardSpells)
                            .addComponent(lblComputerDecision))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPlay1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRule3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDamageOfSpell))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRules2)
                                    .addComponent(lblRules1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRule7)
                                    .addComponent(lblRule4)
                                    .addComponent(lblRule6)
                                    .addComponent(lblRule5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPipsAndMana)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCard)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInstall1)
                            .addComponent(lblInstall2)
                            .addComponent(lblInstall3)
                            .addComponent(lblInstall4)
                            .addComponent(lblHowToInstall))
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHowToPlay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblWhatAreRule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHowToInstall)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstall1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstall2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstall3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInstall4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCard)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPipsAndMana)
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblRule3)
                                            .addComponent(lblDamageOfSpell))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRule4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRule5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRule6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRule7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWhatAreRule)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRules1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRules2)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHowToPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPlay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblScreenShotOfHUD)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlay2)
                                .addGap(71, 71, 71)
                                .addComponent(lblCurrentRound)
                                .addGap(26, 26, 26)
                                .addComponent(lblPassButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblUserDecision)
                                .addGap(62, 62, 62)
                                .addComponent(lblNextRoundBtn)
                                .addGap(53, 53, 53)
                                .addComponent(lblCardSpells)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblComputerDecision)
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblComputerStats)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUserStats)
                                .addGap(23, 23, 23))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmIntroduction myGame = new frmIntroduction(); 
        myGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        myGame.setVisible(true); 
        this.dispose(); 
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUserGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUserGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUserGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUserGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUserGuide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblCardSpells;
    private javax.swing.JLabel lblComputerDecision;
    private javax.swing.JLabel lblComputerStats;
    private javax.swing.JLabel lblCurrentRound;
    private javax.swing.JLabel lblDamageOfSpell;
    private javax.swing.JLabel lblHowToInstall;
    private javax.swing.JLabel lblHowToPlay;
    private javax.swing.JLabel lblInstall1;
    private javax.swing.JLabel lblInstall2;
    private javax.swing.JLabel lblInstall3;
    private javax.swing.JLabel lblInstall4;
    private javax.swing.JLabel lblNextRoundBtn;
    private javax.swing.JLabel lblPassButton;
    private javax.swing.JLabel lblPipsAndMana;
    private javax.swing.JLabel lblPlay1;
    private javax.swing.JLabel lblPlay2;
    private javax.swing.JLabel lblRule3;
    private javax.swing.JLabel lblRule4;
    private javax.swing.JLabel lblRule5;
    private javax.swing.JLabel lblRule6;
    private javax.swing.JLabel lblRule7;
    private javax.swing.JLabel lblRules1;
    private javax.swing.JLabel lblRules2;
    private javax.swing.JLabel lblScreenShotOfHUD;
    private javax.swing.JLabel lblUserDecision;
    private javax.swing.JLabel lblUserStats;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWhatAreRule;
    // End of variables declaration//GEN-END:variables
}
